// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inputs.sql

package database

import (
	"context"
)

const createInput = `-- name: CreateInput :exec
INSERT INTO input (description) VALUES ($1)
`

func (q *Queries) CreateInput(ctx context.Context, description string) error {
	_, err := q.db.ExecContext(ctx, createInput, description)
	return err
}
