// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Input struct {
	ID          int32
	Description string
	Status      sql.NullString
}

type Result struct {
	ID               int32
	WorkerIdentifier string
	Result           string
	Date             sql.NullTime
	InputID          sql.NullInt32
}
